defaults: &defaults
  access_token: "AAAEGxNkGB6sBANaIs48iLuZA7t63fDRYvVZAKCbzpEWNZAv9jIvHhLEZCeK5BiH9ZC1HW3aPJBCtUJe6wDVCnJb5CnBClNGgZD"
  status:
    pending: "p"
    approved: "a"
  role:
    volunteer: "volunteer"
    org_admin: "organization"
    admin: "admin"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults