defaults: &defaults
  status:
    pending: "p"
    approved: "a"
  role:
    volunteer: "volunteer"
    org_admin: "organization"
    admin: "admin"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults