require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganizationAdminsController do

  # This should return the minimal set of attributes required to create a valid
  # OrganizationAdmin. As you add validations to OrganizationAdmin, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all organization_admins as @organization_admins" do
      organization_admin = OrganizationAdmin.create! valid_attributes
      get :index
      assigns(:organization_admins).should eq([organization_admin])
    end
  end

  describe "GET show" do
    it "assigns the requested organization_admin as @organization_admin" do
      organization_admin = OrganizationAdmin.create! valid_attributes
      get :show, :id => organization_admin.id.to_s
      assigns(:organization_admin).should eq(organization_admin)
    end
  end

  describe "GET new" do
    it "assigns a new organization_admin as @organization_admin" do
      get :new
      assigns(:organization_admin).should be_a_new(OrganizationAdmin)
    end
  end

  describe "GET edit" do
    it "assigns the requested organization_admin as @organization_admin" do
      organization_admin = OrganizationAdmin.create! valid_attributes
      get :edit, :id => organization_admin.id.to_s
      assigns(:organization_admin).should eq(organization_admin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrganizationAdmin" do
        expect {
          post :create, :organization_admin => valid_attributes
        }.to change(OrganizationAdmin, :count).by(1)
      end

      it "assigns a newly created organization_admin as @organization_admin" do
        post :create, :organization_admin => valid_attributes
        assigns(:organization_admin).should be_a(OrganizationAdmin)
        assigns(:organization_admin).should be_persisted
      end

      it "redirects to the created organization_admin" do
        post :create, :organization_admin => valid_attributes
        response.should redirect_to(OrganizationAdmin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organization_admin as @organization_admin" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganizationAdmin.any_instance.stub(:save).and_return(false)
        post :create, :organization_admin => {}
        assigns(:organization_admin).should be_a_new(OrganizationAdmin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrganizationAdmin.any_instance.stub(:save).and_return(false)
        post :create, :organization_admin => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organization_admin" do
        organization_admin = OrganizationAdmin.create! valid_attributes
        # Assuming there are no other organization_admins in the database, this
        # specifies that the OrganizationAdmin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrganizationAdmin.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => organization_admin.id, :organization_admin => {'these' => 'params'}
      end

      it "assigns the requested organization_admin as @organization_admin" do
        organization_admin = OrganizationAdmin.create! valid_attributes
        put :update, :id => organization_admin.id, :organization_admin => valid_attributes
        assigns(:organization_admin).should eq(organization_admin)
      end

      it "redirects to the organization_admin" do
        organization_admin = OrganizationAdmin.create! valid_attributes
        put :update, :id => organization_admin.id, :organization_admin => valid_attributes
        response.should redirect_to(organization_admin)
      end
    end

    describe "with invalid params" do
      it "assigns the organization_admin as @organization_admin" do
        organization_admin = OrganizationAdmin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganizationAdmin.any_instance.stub(:save).and_return(false)
        put :update, :id => organization_admin.id.to_s, :organization_admin => {}
        assigns(:organization_admin).should eq(organization_admin)
      end

      it "re-renders the 'edit' template" do
        organization_admin = OrganizationAdmin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrganizationAdmin.any_instance.stub(:save).and_return(false)
        put :update, :id => organization_admin.id.to_s, :organization_admin => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organization_admin" do
      organization_admin = OrganizationAdmin.create! valid_attributes
      expect {
        delete :destroy, :id => organization_admin.id.to_s
      }.to change(OrganizationAdmin, :count).by(-1)
    end

    it "redirects to the organization_admins list" do
      organization_admin = OrganizationAdmin.create! valid_attributes
      delete :destroy, :id => organization_admin.id.to_s
      response.should redirect_to(organization_admins_url)
    end
  end

end
